repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        pass_filenames: false

      - id: black
        name: black
        entry: black --check .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy src
        language: system
        pass_filenames: false
